pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "banguela.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "banguela2.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "banguela3.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "banguela4.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "bloco.jpg"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "Cenario top.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "controle.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "creditos.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragao vermelho.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazuld.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazuld2.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazull.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazull2.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazulr.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazulr2.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazulu.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoazulu2.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoroxod.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoroxol.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoroxor.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoroxou.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoverded.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoverdel.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoverder.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaoverdeu.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaovermelhod.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaovermelhol.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaovermelhor.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "dragaovermelhou.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "grama.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "ninho.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "ninhoA.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "OVOA.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "OVOV.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "time azul.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "time vermelho.png"
pngcrush_1_8_11_w64.exe -ow -rem allb -reduce "Ultimocenario(espero).png"
